name: create-map
on: push

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run build script
      run: |
        git update-index --chmod=+x ./.github/sample.sh
        sh ./.github/sample.sh sucess
      shell: bash
      
