name: create-map
on: push

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run script file
      run: |
        chmod +x "${GITHUB_WORKSPACE}/testing.sh"
    - run: sh ./${GITHUB_WORKSPACE}/testing.sh
      shell: bash
      
