name: create-map
on: push

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    
    - name: Run script file
      run: |
         chmod +x H:/sample/test.sh
         ./H:/sample/test.sh
      shell: bash
