name: create-map
on: push

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run build script
      run: ./.github/sample.sh
      shell: bash
      
